  # Contenedor para la aplicaci칩n de Java. Se genera a partir de la imagen de docker hub, pas치ndole los valores de las variables de entorno
  # Se utiliza el fichero .env para almacenar algunos valores sensible
version:  '3.8'

services:
  java_app:
    image: nsansaturnino/java-app

    container_name: appjava

    restart: always

    environment:
      - DBHOST=database
      - DBPASS=$DBPASSADMIN
      - DBUSER=$DBUSERADMIN
      - DBPORT=3306
      - DBNAME=database1

    ports:
      - 8000:8080

    depends_on:
      - database

  # Contenedor para la BBDD. Se genera a partir de la imagen de mysql en docker hub
  # Se crea un v칩lumen en la m치quina local para guardar y recuperar los datos si el servicio cae
  database:
    image: mysql:5.7
    container_name: basededatos
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=$DBPASSADMIN
      - MYSQL_DATABASE=database1
      - MYSQL_USER=$DBUSER
      - MYSQL_PASSWORD=$DBPASS
    volumes:
      - db_data:/var/lib/mysql
    expose:
      - 3306

volumes:
  db_data: