# Copia el fichero docker compose: coge la imagen de docker hub para la app y crea un contenedor para la BBDD
# Se conecta vía ssh a la máquina AWS y ejecuta docker compose
# La máquina AWS tiene docker instalado

name: CD

on: 
  push:
    branches:
      - tarea8

jobs:
  continous-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_HOST_KEY }}
          source: docker-compose.yaml
          target: /home/ubuntu/
      
      - name: executing remote ssh commands using key
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_HOST_KEY }}
          script: |
            cd /home/ubuntu/docker-compose
            sudo docker compose down
            sudo docker rmi nsansaturnino/java-app
            sudo docker compose up -d